src/main/java/scratch/UCERF3/griddedSeismicity/SectionPolygons.java
src/test/java/scratch/UCERF3/griddedSeismicity/SectionPolygonsTest.java

Trace buffers for faults that turn back on themselves do not always contain the whole fault trace. E.g.:
Because the (red/green) fault curves back against itself in the south, the (blue) buffer polygon is constructed in a faulty way.
This fix will construct the following polygon instead:

fix for trace buffers of faults that turn back on themselves

---

src/main/java/scratch/UCERF3/simulatedAnnealing/ThreadedSimulatedAnnealing.java

closes #40 
I noticed the `ExecutorService` is not simply local to the `iterate` method, not sure what the intention is. I've simply added a `shutdown` method to the class, although I think it's safer to simply always shutdown the service at the end of the `iterate` method.
Alternatively, you might want to consider making the TSA `Closeable`, so that we can use the try-with-resources statement https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html

fixes #40: shutdown ExecutorService

---

src/main/java/org/opensha/commons/geo/Region.java
src/test/java/org/opensha/commons/geo/RegionTest.java

@voj encountered an interesting edge case in our Region code. The following code fails:
```java
LocationList locs = new LocationList();
locs.add(new Location(-45.12780443456831, 168.9986639691212));
locs.add(new Location(-45.1084, 168.9721));
locs.add(new Location(-45.088989411751996, 168.9455540887213));
locs.add(new Location(-45.08892144116412, 168.94548614969298));
locs.add(new Location(-45.05234972943281, 168.89551766538727));
locs.add(new Location(-45.02474975407512, 168.867954596688));
locs.add(new Location(-45.0001497760189, 168.86158746874946));
locs.add(new Location(-44.99628281700839, 168.85910004125023));
locs.add(new Location(-45.032887995374374, 168.90906533699447));
locs.add(new Location(-45.03232462197751, 168.9087027245912));
locs.add(new Location(-45.05233303754178, …
```

Fix for Regions created with non-singular Areas that contain an extra, empty path

---

src/main/java/org/opensha/commons/data/function/EvenlyDiscretizedFunc.java
src/main/java/org/opensha/commons/data/function/XY_DataSet.java
src/main/java/org/opensha/sha/earthquake/faultSysSolution/inversion/constraints/impl/MFDUncertaintyWeightedInversionConstraint.java
src/main/java/org/opensha/sha/earthquake/faultSysSolution/reports/plots/SolMFDPlot.java
src/main/java/scratch/UCERF3/inversion/InversionTargetMFDs.java
src/main/java/scratch/UCERF3/inversion/UCERF3InversionConfiguration.java
src/main/java/scratch/UCERF3/inversion/UCERF3InversionInputGenerator.java
src/main/java/scratch/UCERF3/utils/MFD_InversionConstraint.java
src/main/java/scratch/UCERF3/utils/MFD_WeightedInversionConstraint.java
src/test/java/org/opensha/commons/data/function/EvenlyDiscretizedFuncTest.java
src/test/java/org/opensha/sha/earthquake/faultSysSolution/inversion/constraints/impl/InversionConstraintImplTests.java
src/test/java/scratch/UCERF3/utils/MFD_InversionConstraintAdapterTest.java

This PR create two new classes to support the concept of MFD constraints having weights by bin:
- **MFD_WeightedInversionConstraint** which extends MFD_InversionConstraint, adding the `EvenlyDiscretizedFunc weights;` field
- **MFDUncertaintyWeightedInversionConstraint** which used the above to assign uncertainty weights
It also adds a new method  to EvenlyDiscretizedFunc -  **setYofX** which expects a user defined function (e.g. a lambda function) …  @kevinmilner I did this because so much code using this class does this mapping outside the class, straight after creating an instance.

added new MFD Uncertainty weighted constraint; 

---

src/main/java/org/opensha/commons/gui/plot/PlotLineType.java
src/main/java/org/opensha/sha/earthquake/faultSysSolution/reports/SolidFillPlot.java
src/main/java/org/opensha/sha/earthquake/faultSysSolution/reports/plots/ParticipationRatePlot.java
src/main/java/org/opensha/sha/earthquake/faultSysSolution/reports/plots/SlipRatePlots.java
src/main/java/org/opensha/sha/earthquake/faultSysSolution/ruptures/util/RupSetMapMaker.java

Adds (optional) solid fill to surfaces in `RupSetMapMaker`, with `SlipRatePlots` making use of it.
This is to make subduction plots easier to read. I haven't touched the geojson code, I can make it match if you prefer.
I added a polygon option to `PlotLineType` but didn't change the name to something like `PlotFunType` because I didn't want to change too much.
Here's an example of how filled surface polygons can make outliers easier to spot for a subduction plot:

Added filled polygons to plots 

---

src/main/java/scratch/UCERF3/inversion/InversionFaultSystemRupSet.java

Removed two implementations of average slip from InversionFaultSystemRupSet so that the single source of truth (at least for the implementation) is in the AveSlipModule

deleting redundant average slip implementations

---

src/main/java/scratch/UCERF3/griddedSeismicity/FaultPolyMgr.java

fixes #62
In our edge case, `nodeArea.isEmpty()` returns `false` before the border is cleaned, and `true` after.

fixes #62 getScaledNodeFractions() returns NaN

---

src/main/java/org/opensha/sha/earthquake/faultSysSolution/modules/GridSourceProvider.java
src/main/java/org/opensha/sha/earthquake/faultSysSolution/reports/plots/SolMFDPlot.java
src/main/java/scratch/UCERF3/analysis/CompoundFSSPlots.java
src/main/java/scratch/UCERF3/analysis/FaultSysSolutionERF_Calc.java
src/main/java/scratch/UCERF3/erf/ETAS/ETAS_PrimaryEventSampler.java
src/main/java/scratch/UCERF3/erf/ETAS/ETAS_Simulator.java
src/main/java/scratch/UCERF3/erf/ETAS/ETAS_Utils.java
src/main/java/scratch/UCERF3/erf/ETAS/HaywiredSRL_PaperCalc.java
src/main/java/scratch/UCERF3/erf/ETAS/analysis/ETAS_GriddedNucleationPlot.java
src/main/java/scratch/UCERF3/erf/ETAS/analysis/ETAS_MFD_Plot.java
src/main/java/scratch/UCERF3/erf/FaultSystemSolutionERF.java
src/main/java/scratch/UCERF3/erf/mean/TrueMeanBuilder.java
src/main/java/scratch/UCERF3/griddedSeismicity/AbstractGridSourceProvider.java
src/main/java/scratch/UCERF3/griddedSeismicity/GridSourceFileReader.java
src/main/java/scratch/UCERF3/griddedSeismicity/UCERF3_GridSourceGenerator.java
src/main/java/scratch/UCERF3/griddedSeismicity/UCERF3_NoFaultsGridSourceGenerator.java
src/main/java/scratch/kevin/ucerf3/etas/CacheFileGen.java

This implements refactoring of `GridSourceProvider` method names as requested by @field-usgs, and documentation improvements. Here is a summary of the changes:
* `getSourceSubseismoOnly(...)` ->  `getSourceSubSeisOnFault(...)`
* `getSourceTrulyOffOnly(...)` -> `getSourceUnassociated(...)`
* `getNodeUnassociatedMFD(int)` -> `getMFD_Unassociated(int)`
* `getNodeSubSeisMFD(int)` -> `getMFD_SubSeisOnFault(int)`
* `getNodeMFD(int)` -> `getMFD(int)`
* `scaleAllNodeMFDs(double[])` -> `scaleAllMFDs(double[])`
Ned, I went with the "unassociated" nomenclature (as opposed to "truly off") as it's consistent with the file formats, and also tried to improve documentation to make the definitions more clear. Want to take a look before I merge the changes in?
I think we'll want to either heavily refactor …

GridSourceProvider method refactoring

---

src/main/java/org/opensha/sha/earthquake/faultSysSolution/FaultSystemRupSet.java
src/main/java/org/opensha/sha/earthquake/faultSysSolution/inversion/ClusterSpecificInversionConfigurationFactory.java
src/main/java/org/opensha/sha/earthquake/faultSysSolution/inversion/ClusterSpecificInversionSolver.java
src/main/java/org/opensha/sha/earthquake/faultSysSolution/inversion/InversionConfigurationFactory.java
src/main/java/org/opensha/sha/earthquake/faultSysSolution/inversion/InversionSolver.java
src/main/java/org/opensha/sha/earthquake/faultSysSolution/inversion/Inversions.java
src/main/java/org/opensha/sha/earthquake/faultSysSolution/modules/ConnectivityClusters.java
src/main/java/org/opensha/sha/earthquake/faultSysSolution/modules/InversionMisfitProgress.java
src/main/java/org/opensha/sha/earthquake/faultSysSolution/ruptures/plausibility/impl/prob/JumpProbabilityCalc.java
src/main/java/org/opensha/sha/earthquake/faultSysSolution/ruptures/plausibility/impl/prob/RuptureProbabilityCalc.java
src/main/java/org/opensha/sha/earthquake/faultSysSolution/ruptures/util/ConnectivityCluster.java
src/main/java/org/opensha/sha/earthquake/faultSysSolution/ruptures/util/SegmentationCalculator.java
src/main/java/org/opensha/sha/earthquake/faultSysSolution/util/BranchAverageSolutionCreator.java
src/main/java/org/opensha/sha/earthquake/rupForecastImpl/nshm23/NSHM23_ConstraintBuilder.java
src/main/java/org/opensha/sha/earthquake/rupForecastImpl/nshm23/NSHM23_InvConfigFactory.java
src/main/java/org/opensha/sha/earthquake/rupForecastImpl/nshm23/logicTree/NSHM23_SegmentationModels.java
src/main/java/org/opensha/sha/earthquake/rupForecastImpl/nshm23/logicTree/RupsThroughCreepingSect.java
src/main/java/org/opensha/sha/earthquake/rupForecastImpl/nshm23/logicTree/RupsThroughCreepingSectBranchNode.java
src/main/java/org/opensha/sha/earthquake/rupForecastImpl/nshm23/targetMFDs/SupraSeisBValInversionTargetMFDs.java
src/main/java/org/opensha/sha/earthquake/rupForecastImpl/nshm23/util/AnalyticalSingleFaultInversionSolver.java
src/main/java/org/opensha/sha/earthquake/rupForecastImpl/nshm23/util/ClassicModelInversionSolver.java
src/main/java/scratch/UCERF3/griddedSeismicity/FaultPolyMgr.java

This pull request adds a new "classic" segmentation model to `NSHM23_SegmentationModels`. For the classic model, jumps are only allowed between sections that are part of the same "named fault" (as specified via the `NamedFaults` module). Multi fault clusters (on named faults) are solved via the inversion, but all other faults are now solved analytically.

NSHM23: Support for classic segmentation model, & analytical solution for isolated faults

---

src/main/java/org/opensha/sha/earthquake/rupForecastImpl/PointSourceNshm.java

Port of nshmp-lib `PointSourceFinite` object as `PointSourceNshm`. As far as I can tell there is only one significant difference between this and `PointSource13b`. Constructor for `PointSourceNshm` doesn not need `depths[]` array.

NSHM point source object

---

src/main/java/org/opensha/sha/earthquake/faultSysSolution/hazard/QuickGriddedHazardMapCalc.java
src/main/java/org/opensha/sha/earthquake/faultSysSolution/hazard/mpj/MPJ_LogicTreeHazardCalc.java
src/main/java/org/opensha/sha/earthquake/faultSysSolution/util/SolHazardMapCalc.java

Added a class that can quickly compute hazard maps for gridded seismicity point sources. It does this by first identifying unique gridded seismicity rupture properties (see `UniqueRupture`). Then, for each unique gridded seismicity rupture, we compute conditional exceedance probabilities as a function of site-source distance, and interpolate those for each actual site-source distance.
The calculation happens in reverse of regular hazard calculations: we get the distance-dependent exceedance probabilities for each rupture (computing if necessary, but caching for reuse), and then add the contribution to the curves for each site within the cutoff distance of that rupture.
The expensive part of the calculation here is the interpolation for individual distances. If the number of sites affected …

Efficient gridded seismicity hazard map calculation

---

src/main/java/org/opensha/sha/earthquake/faultSysSolution/ruptures/plausibility/impl/path/PathPlausibilityFilter.java
src/main/java/org/opensha/sha/earthquake/faultSysSolution/ruptures/plausibility/impl/prob/CoulombSectRatioProb.java
src/main/java/org/opensha/sha/earthquake/faultSysSolution/ruptures/strategies/PlausibleClusterConnectionStrategy.java

Low-hanging-fruit performance improvements for rupture building. In my particular case, it reduced a 40 minute runtime to 33 minutes.
These changes are all about bailing out of loops when the result won't change anymore.

Rupture building peformance improvements

---

src/main/java/org/opensha/sha/earthquake/faultSysSolution/ruptures/util/SectIDRange.java
src/test/java/org/opensha/sha/earthquake/faultSysSolution/ruptures/util/RuptureUtilTestSuite.java
src/test/java/org/opensha/sha/earthquake/faultSysSolution/ruptures/util/SectIDRangeTest.java

The particular rupture set that I'm currently investigating has ca 860 fault sub sections and takes ca 40 minutes to build with a 50GB heap which is nearly all used up towards the end.
Looking at the memory usage at 33 minutes, the largest chunk by far is taken up by `SectIDRange` instances:
- 15GB by `short[]` which looks related to `ShortIDRange` since the number of objects is nearly identical (473,958,109 vs 473,958,103)
- 11GB by `SectIDRange:ShortIDRange` 
- 2.5GB by `SectIDRange:SingleID`
Modifications to `SectIDRange`:
- replaced arrays with primitive instance variables
- added `ShortSingleID`
- 473,958,103 individual `ShortIDRange` instances are way too many for 860 sub sections, so I've added caching to ensure that we do not keep multiple identical ranges in memory. For this …

SectIDRange memory usage improvements

---

src/main/java/org/opensha/sha/simulators/stiffness/AggregatedStiffnessCalculator.java

This PR changes the `AggregatedStiffnessCalculator.CACHE_SS2R` constant to an instance variable that can be configured in order to save heap space.
I'm experimenting with creating rupture sets that contain both crustal and subduction faults. We cannot create larger sets at the moment because our heap is flooded with `SectIDRange` arrays, 20GB in this screenshot:
Note how the number of instance matches the number of `UniqueRupture` objects.
I found that setting `AggregatedStiffnessCalculator.CACHE_SS2R` to `false` will completely eliminate this problem with no impact on the running time. A further check showed that our builds actually never have a positive hit for this cache.

Make cacheSs2R optional

---

src/main/java/org/opensha/sha/earthquake/faultSysSolution/FaultSystemRupSet.java

A more memory efficient way to create the `sectionForRups` data structure in the RuptureSet Builder. This makes it possible for us to write large rupture sets.

Using ListWrappers in RupSet Builder

---

src/main/java/org/opensha/sha/earthquake/faultSysSolution/FaultSystemRupSet.java

My apologies, https://github.com/opensha/opensha/pull/113 needs to be partially reverted because magnitude calculation is not necessarily thread safe. This is because `MagAreaRelationship` may set the `rake` property before calculating the magnitude:
https://github.com/opensha/opensha/blob/master/src/main/java/org/opensha/commons/calc/magScalingRelations/MagAreaRelationship.java#L60

MagAreaRelationship is not thread safe

---

src/main/java/org/opensha/commons/data/CSVFile.java
src/main/java/org/opensha/commons/data/CSVReader.java
src/main/java/org/opensha/commons/data/CSVWriter.java
src/main/java/org/opensha/commons/util/modules/helpers/CSV_BackedModule.java
src/main/java/org/opensha/sha/earthquake/faultSysSolution/FaultSystemRupSet.java
src/main/java/org/opensha/sha/earthquake/faultSysSolution/modules/SolutionLogicTree.java
src/test/java/org/opensha/commons/data/CSVReaderTests.java
src/test/java/org/opensha/commons/data/CSVWriterTests.java
src/test/java/org/opensha/commons/data/DataSuite.java

We've started to create large rupture sets while exploring joint ruptures. This is mostly due to the large number of sections in our subduction faults.
This PR introduces a `CSVWriter` and a `CSVReader` that allow us to write the generated ruptures to file without requiring tens of gigabytes of heap. This is mainly achieved by not populating the `List<List<E>> values` property of `CSVFile`. The largest `indices.csv` file we have written with this so far was 4.9GB on disk.

OutputCSVFile for writing large CSV files.

---

src/main/java/scratch/UCERF3/inversion/UCERF3InversionConfiguration.java

We have the requirement to use a different magnitude (8.1) for this piece of code.
We have maintained a branch off `main` for this that we continuously move when pulling from upstream. Moving this functionality into `opensha` would make our life easier.
A static configuration like this is not very pretty, but the function is called from several places, making it impractical to turn this value into a parameter or to pull out the function and maintain a copy in our code base.
If you feel strongly about this we'll keep our branch.

Make normalization magnitude for getSmoothStartingSolution() configurable

---

src/test/java/org/opensha/sha/earthquake/faultSysSolution/modules/StandardFaultSysModulesTest.java

Fixes #134 by closing the `ModuleArchive`'s `'input` explicitly.
@kevinmilner do you think maybe `ModuleArchive` should be `Closeable` instead?

fix issue #134

---

src/main/java/org/opensha/commons/data/WeightedList.java

Fix for https://github.com/opensha/opensha/issues/145
When attempting to normalize all values, if the sum of all weights was zero this would result in a division by zero.
The error message is expected behavior, as normalization is not possible in this case.
This PR improves the error message when this occurs and adds precision checks for already normalized WeightedLists.

Fix normalize bug when all weights sum to zero

---

src/main/java/org/opensha/commons/util/ServerPrefUtils.java

The layout for tracking production servlets used in release/25.4.0 is copied into the main branch to simplify creation of future releases. Still uses the dev backend on main.

Copy release/25.4.0 ServerPrefUtils structure for main

---

src/main/java/org/opensha/sha/earthquake/ERF_Ref.java

Set UCERF3 Epistemic List ERF and NSHM23-WUS ERF to production mode.
This PR ensures that these ERFs will be visible when using the production server. This was manually verified by setting the server prefs. After approval, this PR will merge into opensha/master, ensuring that the ERF is defined as production ready in all branches.
Without further review, opensha/master will be merged into opensha-fork/main, into opensha-fork/release/25.4.0 (omitting server pref changes), into opensha/release/25.4.0. Manual rebuilding on OpenSHA server will occur prior to release.

Set UCERF3 Epistemic and NSHM23-WUS to production mode

---

src/main/java/org/opensha/commons/gui/plot/jfreechart/xyzPlot/XYZDatasetWrapper.java
src/main/java/org/opensha/commons/gui/plot/jfreechart/xyzPlot/XYZPlotSpec.java
src/main/java/org/opensha/sha/faultSurface/utils/GriddedSurfaceUtils.java
src/test/java/org/opensha/sha/faultSurface/utils/DistanceXDiagnosticMap.java

Distance X calculation fix (for #161).
This is ~20x faster than the original OpenSHA DistanceX implementation and more accurate (especially at high latitudes).
Here are some benchmark examples, note that in the prior OpenSHA implementation the +/- cut (where blue turns to red) diverges from the great circle trace extension at high latitudes. The first comparison is at lat=0, so little bias exists in the old calculation; the subsequent test cases are all at high latitude.
| Original | Updated |
|----------|---------|
| ![old_dist_x_test_strike30_random_lat0](https://github.com/user-attachments/assets/31bb2e01-5d4f-4746-b447-d9cf08ef78f8) | ![dist_x_test_strike30_random_lat0](https://github.com/user-attachments/assets/d2968107-1aff-469d-a93c-554f858366fc)|
| …

Distance X calculation fix (for #161)

---

src/main/java/scratch/UCERF3/erf/mean/MeanUCERF3.java

Fixes #169
This hotfix resolves the "file" is null runtime exception in HazardCurveApplication v25.4.0.
The complete model preset is the only Mean UCERF3 Preset where the upperDepthTol == 0d, instead of 100d.
In v1.5.2 this requested the resource, "http://opensha.usc.edu/ftp/ucerf3_erf/cached_dep0.0_depShallow_rakeAll.zip". There is no such file. When there is no file on the server and no cached file, the previous behavior was to load the mean solution.
Similarly, there is no such file or metadata entry on CARC for v25.4.0. The default behavior for GetFile is to throw a NullPointerException, which we forgot to catch in MeanUCERF3.
@kevinmilner Should we build and upload a `cached_dep0.0_depShallow_rakeAll`? This won't require any code changes, so can be made independent of this PR.
This …

Hotfix - Mean UCERF3 ERF (POISSON ONLY LARGE MEM) Complete Model Runtime Exception

---

src/main/java/scratch/UCERF3/erf/mean/MeanUCERF3.java

Fixes #169 
Mean UCERF3 ERF Complete Model Preset in HazardCurveApplication used to create a NullPointerException in v25.4.0. This hotfix marks a minor release v25.4.1, which restores the behavior as found in v1.5.2. The model computes successfully now.

Hotfix minor release - v25.4.1

---

src/main/java/org/opensha/sha/gcim/ui/GcimControlPanel.java

Fixes #174 
In updateIMiDetailsInArrayLists, a new IMikCorrRels is initiated as null, when it should be initiated as a new ArrayList.
Doing so ensures that we don't place null values in the IMikjCorrRelMap in the event that there is a change in the GCIM Calculator while also having zero IMikCorrRels. When trying to flatten the contents of the map into an array, this fails when encountering null instead of a list.
After approval, this hotfix will be merged directly into the latest stable release, backported into our development branch, and new assets will be released for minor release v25.4.2.

Hotfix - Resolve NullPointerException in GCIM Module

---

src/main/java/org/opensha/sha/gcim/ui/GcimControlPanel.java

Backport hotfix for v25.4.2 into main. This fixes a NullPointerException found in the GCIM module when setting the IMR.

Hotfix minor release - v25.4.2

---

src/main/java/org/opensha/commons/gui/plot/GraphPanel.java
src/main/java/org/opensha/commons/gui/plot/jfreechart/JFreeLogarithmicAxis.java
src/main/java/org/opensha/commons/gui/plot/jfreechart/LogPaintScaleLegend.java
src/main/java/org/opensha/commons/gui/plot/jfreechart/xyzPlot/PaintScaleWrapper.java
src/main/java/org/opensha/commons/mapping/gmt/gui/CPTPanel.java
src/main/java/org/opensha/commons/util/cpt/CPT.java
src/main/java/org/opensha/commons/util/cpt/CPTVal.java
src/main/java/org/opensha/sha/earthquake/faultSysSolution/ruptures/util/SegmentationCalculator.java
src/main/java/org/opensha/sha/earthquake/faultSysSolution/util/SubSectionPolygonBuilder.java

This resolves #141, adding support for Log10 colorbars in XYZ plots. I did the implementation slightly differently than proposed in the original issue
The `CPT` class now has `void setLog10(boolean isLog10)` and `boolean isLog10()` methods. Setting the Log10 flag doesn't change any of the interval CPT values, it's just a flag that it is in Log10 space. It does, however, change the behavior of the following methods:
* `Color getColor(double value)`: assumes the passed in value is in linear space, and will be converted to log space before finding the corresponding value
* `double getMinValue()` and `double getMaxValue()`: return the value in linear space, e.g., taking `10^min` if in Log10 mode.
I added new methods to get the raw values without any linear <--> log conversion:
* `Color …

Ability to have logarithmic scales on colorbars for XYZ plots
